# Generated by Django 5.0.7 on 2024-08-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
